server:
  port: 8095
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug

uploadpic:
  path: D:/images
  httpUrl:  http://image.jt.com
redis: 
  redisIp: 192.168.58.129
  redisPort: 6379
  redisnode: 192.168.58.129:6379,192.168.58.129:6380,192.168.58.129:6381
  nodes: 192.168.58.129:7000,192.168.58.129:7001,192.168.58.129:7002,192.168.58.129:7003,192.168.58.129:7004,192.168.58.129:7005
  redisOn: true
runtimeSyslog:
  runOn: false
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-order
  registry:
    address: zookeeper://192.168.58.129:2181?backup=192.168.58.129:2182,192.168.58.129:2183
  protocol:
    name: dubbo
    port: 20882
