#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

logging:
  level:    com.cy: DEBUG
#page
db:
  page:
    pageSize: 10
uploadpic:
  path:  C:/Users/tarena/Desktop/miracle2/miracle2/CGB-DB-SYS-V3.2/target/classes/static/images/